[package]
name = "wikipedia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bzip2 = "0.4.4"
html-escape = "0.2.13"
pandoc = "0.8.11"
parse_wiki_text = "0.1.5"
quick-xml = "0.34.0"
